import Header from '@/components/layouts/header'
import '../globals.css'
import type { Metadata } from 'next'

import Footer from '@/components/layouts/footer'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  )
}


